//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAiopMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANNEEETUDE
    {
        public int ID_ANNEEETUDE { get; set; }
        public string DESCRIPTION_ANNEEETUDE { get; set; }
        public string LIBELLE_ANNEEETUDE { get; set; }
        public Nullable<float> DUREESEANCE_ANNEEETUDE { get; set; }
        public Nullable<int> NBSEANCEAM_ANNEEETUDE { get; set; }
        public Nullable<int> NBSEANCEPM_ANNEEETUDE { get; set; }
    }
}
