//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAiopMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATIMENT
    {
        public BATIMENT()
        {
            this.SALLEs = new HashSet<SALLE>();
        }
    
        public int ID_BATIMENT { get; set; }
        public string LIBELLE_BATIMENT { get; set; }

        public virtual ICollection<SALLE> SALLEs { get; set; }
    }
}
