//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAiopMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARACTERISTIQUE
    {
        public CARACTERISTIQUE()
        {
            this.SALLEs = new HashSet<SALLE>();
            this.RESERVATIONs = new HashSet<RESERVATION>();
        }
    
        public int ID_CARACTERISTIQUE { get; set; }
        public string LIBELLE_CARACTERISTIQUE { get; set; }
    
        public virtual ICollection<SALLE> SALLEs { get; set; }
        public virtual ICollection<RESERVATION> RESERVATIONs { get; set; }
    }
}
