//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAiopMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUR
    {
        public COUR()
        {
            this.ENSEIGNEMENTs = new HashSet<ENSEIGNEMENT>();
        }
    
        public int ID_COURS { get; set; }
        public Nullable<int> ID_MATIERE { get; set; }
        public Nullable<int> ID_TYPE_DE_COURS { get; set; }
        public string LIBELLE_COURS { get; set; }
    
        public virtual MATIERE MATIERE { get; set; }
        public virtual TYPECOUR TYPECOUR { get; set; }
        public virtual ICollection<ENSEIGNEMENT> ENSEIGNEMENTs { get; set; }
    }
}
