//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAiopMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRENAUX
    {
        public CRENAUX()
        {
            this.RESERVATIONs = new HashSet<RESERVATION>();
        }
    
        public int ID_CRENEAU { get; set; }
        public string HEURE_DEBUT { get; set; }
        public string HEURE_FIN { get; set; }

        public string HEURE_DEBUT_AND_HEURE_FIN
        {
            get
            {
                return HEURE_DEBUT + " - " + HEURE_FIN;
            }

        }

        public virtual ICollection<RESERVATION> RESERVATIONs { get; set; }
    }
}
