//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAiopMVC.Models
{
    using System;
    using System.Collections.Generic;
    using ProjetAiopMVC.Models;
    
    public partial class ENSEIGNEMENT
    {
        public ENSEIGNEMENT()
        {
            this.RESERVATIONs = new HashSet<RESERVATION>();
        }
    
        public int ID_ENSEIGNEMENT { get; set; }
        public Nullable<int> ID_COURS { get; set; }
        public Nullable<int> ID_ENSEIGNANT { get; set; }
        public Nullable<int> ID_GROUPE { get; set; }
        public Nullable<int> NB_HEURE_PREVUE { get; set; }

        private AIOPContext db = new AIOPContext();

        public string DESCRIPTION_ENSEIGNEMENT
        {
            get
            {
                string reuslt = db.ENSEIGNANTs.Find(ID_ENSEIGNANT).PRENOM+", "+db.GROUPEs.Find(ID_GROUPE).LIBELLE_GROUPE+", "+db.COURS.Find(ID_COURS).TYPECOUR.LIBELLE_TYPE_DE_COURS+", "+db.MATIEREs.Find(db.COURS.Find(ID_COURS).ID_MATIERE).LIBELLE_MATIERE;
                return reuslt;
            }

        }


    
        public virtual COUR COUR { get; set; }
        public virtual ENSEIGNANT ENSEIGNANT { get; set; }
        public virtual GROUPE GROUPE { get; set; }
        public virtual ICollection<RESERVATION> RESERVATIONs { get; set; }
    }
}
