//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAiopMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ENSEIGNANT
    {
        public ENSEIGNANT()
        {
            this.ENSEIGNEMENTs = new HashSet<ENSEIGNEMENT>();
            this.MATIEREs = new HashSet<MATIERE>();
            this.UEs = new HashSet<UE>();
        }
    
        public int ID_ENSEIGNANT { get; set; }
        [Required]
        [StringLength(30),MinLengthAttribute(3)]
        public string NOM { get; set; }
        [Required]
        public string PRENOM { get; set; }
        
        public string LOGIN { get; set; }
    
        public virtual ICollection<ENSEIGNEMENT> ENSEIGNEMENTs { get; set; }
        public virtual ICollection<MATIERE> MATIEREs { get; set; }
        public virtual ICollection<UE> UEs { get; set; }
    }
}
