//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAiopMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPE
    {
        public GROUPE()
        {
            this.ENSEIGNEMENTs = new HashSet<ENSEIGNEMENT>();
            this.GROUPE1 = new HashSet<GROUPE>();
        }
    
        public int ID_GROUPE { get; set; }
        public Nullable<int> ID_GROUPE_A_POUR_PERE { get; set; }
        public string LIBELLE_GROUPE { get; set; }
    
        public virtual ICollection<ENSEIGNEMENT> ENSEIGNEMENTs { get; set; }
        public virtual ICollection<GROUPE> GROUPE1 { get; set; }
        public virtual GROUPE GROUPE2 { get; set; }
    }
}
