//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAiopMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEMESTRE
    {
        public int ID_SEMESTRE { get; set; }
        public string LIBELLE_SEMESTRE { get; set; }
        public Nullable<int> NIVEAU_SEMESTRE { get; set; }
        public Nullable<int> ID_ANNEEETUDE { get; set; }
    }
}
