//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAiopMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPECOUR
    {
        public TYPECOUR()
        {
            this.COURS = new HashSet<COUR>();
        }
    
        public int ID_TYPE_DE_COURS { get; set; }
        public string LIBELLE_TYPE_DE_COURS { get; set; }
    
        public virtual ICollection<COUR> COURS { get; set; }
    }
}
